[tool.poetry]
name = "playwright-python"
version = "0.1.0"
description = ""
authors = ["nirtal85 <nirt236@gmail.com>"]
readme = "README.md"
packages = [{include = "playwright_python"}]

[tool.isort]
skip = ["env", "venv"]
profile = "black"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
isort = "5.12.0"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
base_url = 'https://www.saucedemo.com/'
addopts = [
    "--alluredir=allure-results",
    "-ra",
    "--color=yes",
    "--headed",
    "--video=retain-on-failure",
]

[tool.poetry.dependencies]
python = "^3.11"
allure-pytest = "2.13.2"
allure-python-commons = "2.13.2"
pytest = "7.4.0"
requests = "2.31.0"
playwright = "1.40.0"
pytest-playwright = "0.4.3"
pytest-base-url = "^2.0.0"
nursery = "^0.0.1a1"
trio = "^0.24.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
